user  www;
#Defines which Linux system user will own and run the Nginx server

worker_processes  1;
#Referes to single threaded process. Generally set to be equal to the number of CPUs or cores.

error_log  /var/log/nginx/error.log; #error_log  logs/error.log  notice;
#Specifies the file where server logs. 

#pid        logs/nginx.pid;
#nginx will write its master process ID(PID).

events {
    worker_connections  1024;
}

http {
	include mime.types;
	default_type application/octet-stream;
	sendfile on;

	## redirection http -> https
	server {
		listen 80;
		server_name localhost;
		return 301 https://$host$request_uri;
	}

	server {
		listen       443 ssl;
		server_name  localhost;
		root  /www/wordpress;
		index index index.php index.html index.htm;
		client_max_body_size 500M;

		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_certificate      /etc/nginx/ssl/server.crt;
		ssl_certificate_key  /etc/nginx/ssl/server.key;
		ssl_session_cache    shared:SSL:1m;
		ssl_session_timeout  5m;
		ssl_ciphers  HIGH:!aNULL:!MD5;
		ssl_prefer_server_ciphers  on;

		location / {
			try_files $uri $uri/ /index.php?$args;
		}
		
		location ~ \.php$ {
			include snippets/fastcgi-php.conf;
			fastcgi_pass   wordpress:9000;
		}

		location = /favicon.ico {
			log_not_found off;
			access_log off;
		}

		location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
			expires max;
			log_not_found off;
		}

		location = /robots.txt {
			allow all;
			log_not_found off;
			access_log off;
		}
	}

}
